all:
	gcc -Wall -Wextra -Werror -g3 -c ft_bzero.c ft_calloc.c ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c mmu.c mmu_utils.c
	mv ft_bzero.o ft_calloc.o ft_memchr.o ft_memcmp.o ft_memcpy.o ft_memmove.o ft_memset.o mmu.o mmu_utils.o ../../obj
