name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Get dependencies
        run: sudo apt update && sudo apt install build-essential libx11-dev libglfw3-dev libglfw3 xorg-dev
      - name: make cub3d
        run: |
          make
          if [ $? -ne 0 ]
          then
            echo "::error::Command failed - ❌"
          fi
      - name: success
        run: echo "Success"
